version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1.4
jobs:
  continuous-integration:
    docker:
      - image: cimg/base:stable
    resource_class: medium
    steps:
      - setup_remote_docker:
          docker_layer_caching: true

      - checkout

      - run:
          name: Install Docker
          command: |
            sudo apt-get update
            sudo apt-get install -y docker.io

      - aws-ecr/build-and-push-image:
          create-repo: true
          dockerfile: ./Dockerfile
          path: .
          platform: linux/amd64
          push-image: true
          region: '${AWS_REGION}'
          repo: demo
          registry-id: AWS_ECR_REGISTRY_ID
          repo-scan-on-push: true
          tag: latest

  continuous-delivery:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - setup_remote_docker

      - checkout

      - run:
          name: Install Docker
          command: |
            sudo apt-get update
            sudo apt-get install -y docker.io
            sudo usermod -aG docker $USER
            newgrp docker

      - aws-cli/setup

      - run:
          name: auth to aws ecr
          command: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 802898747809.dkr.ecr.us-east-1.amazonaws.com
          
      - run:
          name: pull image from private repository
          command: docker pull 802898747809.dkr.ecr.us-east-1.amazonaws.com/hatespeechdemo:latest
          
      - run:
          name: run image
          command: docker run -d -p 8080:8080 802898747809.dkr.ecr.us-east-1.amazonaws.com/hatespeechdemo:latest
workflows:
  CICD:
    jobs:
      - continuous-integration
      - continuous-delivery:
          requires:
            - continuous-integration
